
services:
  nande:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nande
    privileged: true
    environment:
      WEB_PORT: 6643
      EXTENSION_FOLDER: extensions
      INFLUX_URL: http://influxdb:8086
      INFLUX_TOKEN: superscecrettoken
      INFLUX_ORG: nande
      INFLUX_BUCKET: nande
      GRAFANA_TOKEN: glsa_neyOrwiCERldkxlUy5VfqaDjODEVDJKs_e1d2f3a1
      GRAFANA_URL: http://grafana:3000
      GRAFANA_INFLUX_DATASOURCE_ID: aeg13b6nhlse8b
    ports:
      - "6643:6643"
    networks:
      nande-network:
    devices:
      - "/dev/sd*:/dev/sd*"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dev-volume:/app/extensions
      - /media/HDD:/mnt/disk1  # Here enter the disk for the smartctl extension
      - /media/Games:/mnt/disk2
    restart: always
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    environment:
      - INFLUXDB_DB=nande
      - INFLUXDB_HTTP_BIND_ADDRESS=:8086
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=Password
      - DOCKER_INFLUXDB_INIT_ORG=nande
      - DOCKER_INFLUXDB_INIT_BUCKET=nande
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=superscecrettoken
    ports:
      - "8086:8086"
    networks:
      nande-network:
    volumes:
      - influxdb-data:/var/lib/influxdb
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: '0'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      nande-network:
    depends_on:
      - influxdb
    volumes:
      - grafana-data:/var/lib/grafana
    restart: always

networks:
  nande-network:
volumes:
  influxdb-data:
  grafana-data: