
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_DB=nande
      - INFLUXDB_HTTP_BIND_ADDRESS=:8086
    ports:
      - "8086:8086"   # InfluxDB port
    volumes:
      - influxdb-data:/var/lib/influxdb   # Persist data
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Set admin password
    ports:
      - "3000:3000"   # Grafana port
    depends_on:
      - influxdb
    volumes:
      - grafana-data:/var/lib/grafana   # Persist Grafana data
    restart: always

volumes:
  influxdb-data:
  grafana-data: