{
 "title": "Nande-Smartctl",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Overall Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Drive Count",
   "type": "stat",
   "description": "The number of drives",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nande\")\n  |> range(start: -1d)  // Adjust the time range as needed\n  |> filter(fn: (r) => r._measurement == \"smartctl\")\n  |> keep(columns: [\"serial\"]) \n  |> distinct(column: \"serial\")\n  |> group(columns: [])\n  |> count()\n  |> yield(name: \"count\")"
    }
   ]
  },
  {
   "title": "Drive Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "healthQuery = from(bucket: \"nande\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"smartctl\")\n  |> filter(fn: (r) => r[\"_field\"] == \"health\")\n  |> last()\n  |> group(columns: [\"model\", \"serial\"])\n  |> map(fn: (r) => ({r with \"drive\": r.model + \" \" + r.serial, \"status\": r._value}))\n  |> keep(columns: [\"drive\", \"status\"])\n  |> rename(columns: {drive: \"Drive\"})\n  |> rename(columns: {status: \"Status\"})\n\ncapacityQuery = from(bucket: \"nande\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"smartctl\")\n  |> filter(fn: (r) => r[\"_field\"] == \"capacity\")\n  |> last()\n  |> group(columns: [\"model\", \"serial\"])\n  |> map(fn: (r) => ({r with \"drive\": r.model + \" \" + r.serial, \"capacity\": r._value}))\n  |> keep(columns: [\"drive\", \"capacity\"])\n  |> rename(columns: {drive: \"Drive\"})\n  |> rename(columns: {capacity: \"Capacity\"})\n\n\nspaceUsedQuery = from(bucket: \"nande\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"smartctl\")\n  |> filter(fn: (r) => r[\"_field\"] == \"space_used\")\n  |> last()\n  |> group(columns: [\"model\", \"serial\"])\n  |> map(fn: (r) => ({r with \"drive\": r.model + \" \" + r.serial, \"space_used\": r._value}))\n  |> keep(columns: [\"drive\", \"space_used\"])\n  |> rename(columns: {drive: \"Drive\"})\n  |> rename(columns: {space_used: \"Space Used\"})\n\ntempQuery = from(bucket: \"nande\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"smartctl\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> last()\n  |> group(columns: [\"model\", \"serial\"])\n  |> map(fn: (r) => ({r with \"drive\": r.model + \" \" + r.serial, \"temperature\": r._value}))\n  |> keep(columns: [\"drive\", \"temperature\"])\n  |> rename(columns: {drive: \"Drive\"})\n  |> rename(columns: {temperature: \"Temperature\"})\n\nfirstJoin = join(\n  tables: {healthQuery: healthQuery, spaceUsedQuery: spaceUsedQuery},\n  on: [\"Drive\"],\n  method: \"inner\"\n)\n|> keep(columns: [\"Drive\", \"Status\", \"Space Used\"])\n\nsecondJoin = join(\n  tables: {firstJoin: firstJoin, capacityQuery: capacityQuery},\n  on: [\"Drive\"],\n  method: \"inner\"\n)\n|> keep(columns: [\"Drive\", \"Status\", \"Space Used\",\"Capacity\"])\n\njoin(\n  tables: {secondJoin: secondJoin, tempQuery: tempQuery},\n  on: [\"Drive\"],\n  method: \"inner\"\n)\n|> keep(columns: [\"Drive\", \"Status\", \"Space Used\",\"Capacity\",\"Temperature\"])\n\n\n"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nande\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"smartctl\")\n  |> filter(fn: (r) => r._field == \"health\" and r._value == 0) \n  |> keep(columns: [\"serial\"]) \n  |> distinct(column: \"serial\")\n  |> group(columns: [])\n  |> count()\n  |> yield(name: \"count\")"
    }
   ]
  },
  {
   "title": "Healthy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nande\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"smartctl\")\n  |> filter(fn: (r) => r._field == \"health\" and r._value == 1) \n  |> keep(columns: [\"serial\"]) \n  |> distinct(column: \"serial\")\n  |> group(columns: [])\n  |> count()\n  |> yield(name: \"count\")"
    }
   ]
  },
  { "title": "Drive {Name}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nande\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"smartctl\")\n  |> filter(fn: (r) => r[\"_field\"] == \"health\")\n  |> filter(fn: (r) => r[\"serial\"] == \"ZFN4H7A6\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> last()\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Prefailure Count",
   "type": "stat",
   "description": "The amount of smart attribute with the prefailure flag enabled",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nande\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"smartctl\")\n  |> filter(fn: (r) => r[\"_field\"] == \"prefailure_count\")\n  |> filter(fn: (r) => r[\"serial\"] == \"ZFN4H7A6\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> last()\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"nande\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"smartctl\")\n  |> filter(fn: (r) => r[\"_field\"] == \"space_used\")\n  |> filter(fn: (r) => r[\"serial\"] == \"ZFN4H7A6\")\n  |> aggregateWindow(every: 30s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Total Disk Read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"nande\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"smartctl\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_bytes_read\")\n  |> filter(fn: (r) => r[\"serial\"] == \"ZFN4H7A6\")\n  |> aggregateWindow(every: 30s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Total Disk Write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"nande\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"smartctl\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_bytes_written\")\n  |> filter(fn: (r) => r[\"serial\"] == \"ZFN4H7A6\")\n  |> aggregateWindow(every: 30s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Power on Hours",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nande\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"smartctl\")\n  |> filter(fn: (r) => r[\"_field\"] == \"power_on_hours\")\n  |> filter(fn: (r) => r[\"serial\"] == \"ZFN4H7A6\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> last()\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Load Cycles",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nande\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"smartctl\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_cycle_count\")\n  |> filter(fn: (r) => r[\"serial\"] == \"ZFN4H7A6\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> last()\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Power Cycles",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nande\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"smartctl\")\n  |> filter(fn: (r) => r[\"_field\"] == \"power_cycles\")\n  |> filter(fn: (r) => r[\"serial\"] == \"ZFN4H7A6\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> last()\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Head Flying Hours",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nande\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"smartctl\")\n  |> filter(fn: (r) => r[\"_field\"] == \"head_flying_hours\")\n  |> filter(fn: (r) => r[\"serial\"] == \"ZFN4H7A6\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> last()\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"nande\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"smartctl\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_read_since_period\")\n  |> filter(fn: (r) => r[\"serial\"] == \"ZFN4H7A6\")\n  |> aggregateWindow(every: 30s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"nande\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"smartctl\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_written_since_period\")\n  |> filter(fn: (r) => r[\"serial\"] == \"ZFN4H7A6\")\n  |> aggregateWindow(every: 30s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}